-- Reference table: Company roles
-- Data loaded from CSV: company_roles.csv (generated by silver_to_gold.py)
CREATE TABLE IF NOT EXISTS public.company_roles (
        id INT PRIMARY KEY,
        role_name VARCHAR(50) NOT NULL UNIQUE
    );