-- Reference table: Farm types
-- Data loaded from CSV: farm_types.csv (generated by silver_to_gold.py)
CREATE TABLE IF NOT EXISTS public.farm_types (
        id INT PRIMARY KEY,
        type_title VARCHAR(50) NOT NULL UNIQUE
    );