-- Reference table: Person roles
-- Data loaded from CSV: person_roles.csv (generated by silver_to_gold.py)
CREATE TABLE IF NOT EXISTS public.person_roles (
        id INT PRIMARY KEY,
        role_name VARCHAR(50) NOT NULL UNIQUE
    );