-- ORDRE D'EXECUTION SEPARE POUR MICROSOFT ACCESS
-- ==============================================
-- 
-- ETAPE 1: Créer toutes les tables SANS contraintes FOREIGN KEY
-- ETAPE 2: Ajouter les contraintes FOREIGN KEY via le script foreign_keys.sql
--
-- IMPORTANT: Microsoft Access ne supporte pas les CREATE TABLE avec FOREIGN KEY
-- via ODBC. Il faut donc créer les tables d'abord, puis ajouter les contraintes.

-- ================================================================
-- ETAPE 1: CREATION DES TABLES (dans l'ordre - sans FOREIGN KEY)
-- ================================================================

-- 1. Tables de référence (lookups) - Aucune dépendance
-- farm_types.sql
-- person_roles.sql  
-- company_roles.sql
-- maintenance_types.sql
-- ice_detection_systems.sql

-- 2. Tables d'entités principales
-- persons.sql
-- employees.sql
-- companies.sql
-- farms.sql

-- 3. Tables dépendantes des entités principales
-- substations.sql (dépend de farms)

-- 4. Tables complexes avec multiples dépendances
-- wind_turbine_generators.sql (dépend de farms, substations, companies)
-- tcma_contracts.sql (dépend de farms)
-- tariffs.sql (dépend de farms)

-- 5. Tables de relation
-- farm_company_roles.sql (dépend de farms, companies, company_roles)
-- farm_ice_detection_systems.sql (dépend de farms, ice_detection_systems)
-- farm_referents.sql (dépend de farms, person_roles, persons, companies)

-- 6. Tables de détails (dépendent de farms)
-- drei.sql (dépend de farms, companies)
-- icpe.sql (dépend de farms)
-- farm_statuses.sql (dépend de farms)
-- farm_locations.sql (dépend de farms)
-- wind_farm_turbine_details.sql (dépend de farms)
-- farm_substation_details.sql (dépend de farms, companies)
-- farm_operation_maintenances.sql (dépend de farms)
-- farm_administrations.sql (dépend de farms)
-- farm_target_performances.sql (dépend de farms)
-- farm_actual_performances.sql (dépend de farms)
-- farm_financial_guarantees.sql (dépend de farms)
-- farm_legal_auditors.sql (dépend de farms, companies)

-- 7. Tables orphelines
-- maintenances.sql (aucune dépendance)

-- ================================================================
-- ETAPE 2: AJOUT DES CONTRAINTES FOREIGN KEY
-- ================================================================
-- UNE FOIS TOUTES LES TABLES CREES, EXECUTER:
-- foreign_keys.sql

-- ================================================================
-- RESUME DE L'ORDRE D'EXECUTION:
-- ================================================================
-- 1. Executer tous les scripts .sql dans l'ordre ci-dessus (sans FK)
-- 2. Executer foreign_keys.sql pour ajouter toutes les contraintes
-- 
-- Exemple de code Python:
-- 
-- import pathlib
-- import pyodbc
-- 
-- # ETAPE 1: Creer les tables
-- table_files = [
--     'farm_types.sql', 'person_roles.sql', 'company_roles.sql',
--     'maintenance_types.sql', 'ice_detection_systems.sql',
--     'persons.sql', 'employees.sql', 'companies.sql', 'farms.sql',
--     'substations.sql', 'wind_turbine_generators.sql', 'tcma_contracts.sql',
--     'tariffs.sql', 'farm_company_roles.sql', 'farm_ice_detection_systems.sql',
--     'farm_referents.sql', 'drei.sql', 'icpe.sql', 'farm_statuses.sql',
--     'farm_locations.sql', 'wind_farm_turbine_details.sql', 
--     'farm_substation_details.sql', 'farm_operation_maintenances.sql',
--     'farm_administrations.sql', 'farm_target_performances.sql',
--     'farm_actual_performances.sql', 'farm_financial_guarantees.sql',
--     'farm_legal_auditors.sql', 'maintenances.sql'
-- ]
-- 
-- with pyodbc.connect(connection_string) as cnxn:
--     cursor = cnxn.cursor()
--     for file in table_files:
--         sql_content = pathlib.Path(f'src/database/models/{file}').read_text()
--         cursor.execute(sql_content)
--     cnxn.commit()
-- 
-- # ETAPE 2: Ajouter les contraintes foreign key
-- foreign_keys_content = pathlib.Path('src/database/models/foreign_keys.sql').read_text()
-- with pyodbc.connect(connection_string) as cnxn:
--     cursor = cnxn.cursor()
--     for statement in foreign_keys_content.split(';'):
--         if statement.strip():
--             cursor.execute(statement)
--     cnxn.commit()